[package]
name = "amd-efs"
version = "0.1.0"
authors = ["dannym"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amd-flash = { path = "../amd-flash" }
byteorder = "1.4.3"
modular-bitfield = "0.11.2"

#
# In order to use macros as discriminants in enums that make use of derive
# macros (e.g., AsBytes, FromPrimitive), we need the syn crate to have "full"
# enabled. The easiest way to do this is to use num-derive's "full-syntax",
# which passes "full" through to syn.
#
num-derive = { version = "0.3.0", features = [ "full-syntax" ] }
num-traits = { version = "0.2.12", default-features = false }
zerocopy = "0.5.0"

[features]
default = []
std = []
